---
- name: Testing with Cisco IMC
  hosts: tower
  become: false
  gather_facts: false
  tasks:
    - name: Vmedia mount
      imc_rest:
        hostname: '{{ imc_hostname }}'
        username: '{{ imc_username }}'
        password: '{{ imc_password }}'
        validate_certs: no
        content: |
          <!-- Configure vmedia mount -->
          <configConfMo dn="sys/svc-ext/vmedia-svc/vmmap-Linux" inHierarchical="false"><inConfig>
            <commVMediaMap dn="sys/svc-ext/vmedia-svc/vmmap-Linux" map="www" mountOptions="username=,password=" remoteFile="{{ HSTNAME }}.iso" remoteShare="http://10.13.61.74/iso/" status="created" volumeName="Linux"/>
          </inConfig></configConfMo>  
      delegate_to: localhost
