---
- name: Drift change 
  hosts: check
  become: true

  roles:
    - group.role
    - user.role
  tasks:
    - name: Recommended sysctl
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: no
#      ignoreerrors: yes
      with_items: "{{ config_sysctl }}"

